const test1 = [
  {
    name: "Lemon Herb Grilled Chicken with Quinoa and Broccoli",
    cooking_time: "30 minutes",
    calories: "550",
    macros: { protein: "40 grams", carbs: "36 grams", total_fat: "18 grams", saturated_fat: "4 grams" },
    ingredients: [
      "500g (1.1 lbs) chicken breast",
      "1 cup quinoa (170g)",
      "2 cups broccoli florets (150g)",
      "2 tablespoons olive oil",
      "1 lemon, juiced",
      "1 tablespoon dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Marinate the chicken in olive oil, lemon juice, oregano, salt, and pepper for at least 30 minutes.",
      "Cook quinoa according to package instructions.",
      "Steam the broccoli until tender, about 5-7 minutes.",
      "Grill the marinated chicken for 6-7 minutes on each side or until fully cooked.",
    ],
    weekend_prep: [
      "Marinate chicken in advance and store in the fridge.",
      "Cook quinoa and store in an airtight container.",
      "Chop broccoli and store in a ziplock bag.",
    ],
    weekday_cooking: ["Heat the pre-cooked quinoa in a pan.", "Steam broccoli for 5 minutes.", "Grill the marinated chicken."],
    difficulty: "Intermediate",
    dietary_info: ["gluten-free", "high-protein", "low-carb"],
  },
  {
    name: "Spicy Shrimp Stir-Fry with Bell Peppers and Cauliflower Rice",
    cooking_time: "30 minutes",
    calories: "490",
    macros: { protein: "38 grams", carbs: "25 grams", total_fat: "22 grams", saturated_fat: "5 grams" },
    ingredients: [
      "400g (14 oz) shrimp, peeled and deveined",
      "2 cups cauliflower rice (200g)",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon sriracha",
      "1 tablespoon sesame oil",
      "2 green onions, chopped",
    ],
    instructions: [
      "In a bowl, mix soy sauce, sriracha, and sesame oil; add shrimp to marinate for 15 minutes.",
      "Stir-fry the bell peppers in a pan for 5 minutes until tender.",
      "Add marinated shrimp to the pan and cook until shrimp are pink, about 3-4 minutes.",
      "Serve over cauliflower rice.",
    ],
    weekend_prep: [
      "Marinate shrimp in soy sauce and sriracha and store in the fridge.",
      "Prepare cauliflower rice and store in an airtight container.",
      "Chop bell peppers and green onions, storing them in the fridge.",
    ],
    weekday_cooking: [
      "Stir-fry the pre-cooked cauliflower rice until heated through.",
      "Quickly stir-fry the bell peppers and shrimp.",
      "Serve the shrimp stir-fry over the cauliflower rice.",
    ],
    difficulty: "Intermediate",
    dietary_info: ["low-carb", "high-protein", "dairy-free"],
  },
  {
    name: "Beef and Vegetable Skewers with Couscous",
    cooking_time: "30 minutes",
    calories: "600",
    macros: { protein: "45 grams", carbs: "40 grams", total_fat: "25 grams", saturated_fat: "7 grams" },
    ingredients: [
      "500g (1.1 lbs) beef sirloin, cubed",
      "1 zucchini, sliced",
      "1 bell pepper, cubed",
      "1 red onion, cubed",
      "1 cup couscous (160g)",
      "2 tablespoons olive oil",
      "1 teaspoon garlic powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat grill or grill pan.",
      "In a bowl, combine beef, zucchini, bell pepper, onion, olive oil, garlic powder, salt, and pepper.",
      "Thread beef and vegetables onto skewers.",
      "Grill skewers for 10-12 minutes, turning occasionally until cooked to desired doneness.",
      "Prepare couscous according to package instructions.",
    ],
    weekend_prep: [
      "Cube beef and marinate with olive oil, garlic powder, salt, and pepper.",
      "Chop vegetables and store in a ziplock bag.",
      "Pre-cook couscous and store in an airtight container.",
    ],
    weekday_cooking: ["Thread marinated beef and vegetables onto skewers.", "Grill skewers and heat couscous."],
    difficulty: "Intermediate",
    dietary_info: ["high-protein", "low-carb", "dairy-free"],
  },
  {
    name: "Honey Mustard Baked Salmon with Asparagus",
    cooking_time: "30 minutes",
    calories: "520",
    macros: { protein: "38 grams", carbs: "30 grams", total_fat: "25 grams", saturated_fat: "5 grams" },
    ingredients: [
      "500g (1.1 lbs) salmon fillets",
      "1 bunch asparagus (250g)",
      "2 tablespoons honey",
      "1 tablespoon Dijon mustard",
      "1 tablespoon olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat the oven to 200°C (400°F).",
      "In a small bowl, mix honey, Dijon mustard, olive oil, salt, and pepper.",
      "Place salmon on a baking tray lined with parchment paper; brush the mixture over the salmon.",
      "Add asparagus around the salmon, drizzling with olive oil, salt, and pepper.",
      "Bake for 15-20 minutes or until salmon is cooked through.",
    ],
    weekend_prep: [
      "Mix honey mustard sauce and store in the fridge.",
      "Trim asparagus and store in a ziplock bag.",
      "Portion salmon fillets and store in the fridge.",
    ],
    weekday_cooking: ["Preheat the oven.", "Place salmon and asparagus on a tray, brush with sauce, and bake."],
    difficulty: "Intermediate",
    dietary_info: ["high-protein", "low-carb", "dairy-free"],
  },
];

const test2 = [
  {
    name: "Spinach and Feta Omelette",
    cooking_time: "15 minutes",
    calories: "320",
    macros: { protein: "23 grams", carbs: "12 grams", total_fat: "18 grams", saturated_fat: "6 grams" },
    ingredients: [
      "4 large eggs",
      "100g (3.5 oz) feta cheese, crumbled",
      "1 cup fresh spinach, chopped",
      "1 medium bell pepper, diced",
      "1 tablespoon olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a bowl, whisk together the eggs, salt, and pepper.",
      "Heat olive oil in a non-stick skillet over medium heat.",
      "Add diced bell pepper and sauté for 3-4 minutes until soft.",
      "Add chopped spinach and cook until wilted, about 2 minutes.",
      "Pour the egg mixture over the vegetables, and cook until the edges begin to set.",
      "Sprinkle feta cheese over the top, then fold the omelette in half and cook for another minute.",
    ],
    weekend_prep: ["Chop the spinach and bell pepper.", "Crack the eggs into a container and whisk with salt and pepper."],
    weekday_cooking: ["Heat the skillet with olive oil.", "Add prepped vegetables and cook as directed, then add egg mixture."],
    difficulty: "Intermediate",
    dietary_info: ["gluten-free", "low-carb", "high-protein"],
  },
  {
    name: "Banana Oatmeal Protein Bowl",
    cooking_time: "10 minutes",
    calories: "450",
    macros: { protein: "22 grams", carbs: "50 grams", total_fat: "12 grams", saturated_fat: "3 grams" },
    ingredients: [
      "1 cup rolled oats",
      "2 cups almond milk",
      "1 medium banana, sliced",
      "2 tablespoons almond butter",
      "1 scoop vanilla protein powder",
      "1 teaspoon cinnamon",
    ],
    instructions: [
      "In a saucepan, combine the rolled oats and almond milk, bring to a boil.",
      "Reduce heat and simmer for 5 minutes, stirring occasionally.",
      "Stir in protein powder and cinnamon until well mixed.",
      "Serve topped with sliced banana and almond butter.",
    ],
    weekend_prep: ["Pre-portion rolled oats into containers.", "Slice banana and store in an airtight container in the fridge."],
    weekday_cooking: [
      "Combine pre-portioned oats and almond milk in a saucepan and cook as directed.",
      "Top with banana and almond butter before serving.",
    ],
    difficulty: "Intermediate",
    dietary_info: ["vegan", "gluten-free", "high-protein"],
  },
  {
    name: "Breakfast Burrito with Black Beans and Veggies",
    cooking_time: "25 minutes",
    calories: "480",
    macros: { protein: "24 grams", carbs: "45 grams", total_fat: "15 grams", saturated_fat: "4 grams" },
    ingredients: [
      "2 whole wheat tortillas (8-inch)",
      "200g (7 oz) canned black beans, rinsed",
      "100g (3.5 oz) corn, frozen",
      "1 medium zucchini, diced",
      "1 medium onion, diced",
      "2 large eggs",
      "1 tablespoon olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a skillet over medium heat.",
      "Add onion and zucchini, sauté until softened, about 5 minutes.",
      "Stir in black beans and corn, and cook for another 2-3 minutes.",
      "In a bowl, whisk the eggs and pour them over the veggies, scrambling until cooked.",
      "Spoon filling into tortillas, roll them up, and serve.",
    ],
    weekend_prep: ["Chop zucchini and onion.", "Rinse and portion black beans and corn into containers."],
    weekday_cooking: ["Heat prepped vegetables and beans in a skillet.", "Scramble eggs and assemble burritos."],
    difficulty: "Intermediate",
    dietary_info: ["vegetarian", "high-protein", "low-carb"],
  },
  {
    name: "Berry Protein Smoothie Bowl",
    cooking_time: "10 minutes",
    calories: "350",
    macros: { protein: "25 grams", carbs: "45 grams", total_fat: "9 grams", saturated_fat: "2 grams" },
    ingredients: [
      "1 cup mixed berries (strawberries, blueberries, raspberries)",
      "1 banana",
      "1 cup unsweetened almond milk",
      "1 scoop whey protein powder",
      "1 tablespoon chia seeds",
      "1/2 cup spinach, packed",
    ],
    instructions: [
      "In a blender, combine mixed berries, banana, almond milk, protein powder, and spinach.",
      "Blend until smooth, then pour into a bowl.",
      "Top with chia seeds and additional berries if desired.",
    ],
    weekend_prep: ["Pre-portion mixed berries and slice banana.", "Chop spinach and store in an airtight container."],
    weekday_cooking: ["Blend all ingredients and pour into a bowl.", "Add toppings as desired."],
    difficulty: "Intermediate",
    dietary_info: ["gluten-free", "vegan-option", "high-protein"],
  },
];
